apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    meta.helm.sh/release-name: minecraft
    meta.helm.sh/release-namespace: minecraft-server
  creationTimestamp: "2024-05-21T06:27:01Z"
  generation: 5
  labels:
    app: minecraft-minecraft
    app.kubernetes.io/instance: minecraft-minecraft
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: minecraft
    app.kubernetes.io/version: 4.17.0
    chart: minecraft-4.17.0
    heritage: Helm
    release: minecraft
  name: minecraft-minecraft
  namespace: minecraft-server
  resourceVersion: "29072"
  uid: c82d99c0-9138-46f4-a918-b61baae057e0
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: minecraft-minecraft
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: minecraft-minecraft
        app.kubernetes.io/instance: minecraft-minecraft
        app.kubernetes.io/name: minecraft
        app.kubernetes.io/version: 4.17.0
    spec:
      containers:
      - env:
        - name: EULA
          value: "true"
        - name: TYPE
          value: VANILLA
        - name: VERSION
          value: LATEST
        - name: DIFFICULTY
          value: peaceful
        - name: MAX_PLAYERS
          value: "20"
        - name: MAX_WORLD_SIZE
          value: "10000"
        - name: MAX_BUILD_HEIGHT
          value: "256"
        - name: MAX_TICK_TIME
          value: "60000"
        - name: SPAWN_PROTECTION
          value: "16"
        - name: VIEW_DISTANCE
          value: "10"
        - name: MODE
          value: creative
        - name: MOTD
          value: Welcome to Minecraft on Kubernetes!
        - name: LEVEL_TYPE
          value: DEFAULT
        - name: LEVEL
          value: world
        - name: MODRINTH_ALLOWED_VERSION_TYPE
          value: release
        - name: MEMORY
          value: 1024M
        - name: OVERRIDE_SERVER_PROPERTIES
          value: "false"
        - name: ENABLE_RCON
          value: "false"
        image: itzg/minecraft-server:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - mc-health
          failureThreshold: 20
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: minecraft-minecraft
        ports:
        - containerPort: 25565
          name: minecraft
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - mc-health
          failureThreshold: 20
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: "1"
            memory: 1280Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /tmp
          name: tmp
        - mountPath: /data
          name: datadir
        - mountPath: /backups
          name: backupdir
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 2000
        runAsGroup: 3000
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: tmp
      - emptyDir: {}
        name: datadir
      - emptyDir: {}
        name: backupdir
status:
  conditions:
  - lastTransitionTime: "2024-05-21T06:27:02Z"
    lastUpdateTime: "2024-05-21T06:47:17Z"
    message: ReplicaSet "minecraft-minecraft-84c6b8cdf5" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2024-05-22T21:28:08Z"
    lastUpdateTime: "2024-05-22T21:28:08Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 5
