---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - minecraft.k8s.learning.yodo.dev
  resources:
  - servers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - minecraft.k8s.learning.yodo.dev
  resources:
  - servers/finalizers
  verbs:
  - update
- apiGroups:
  - minecraft.k8s.learning.yodo.dev
  resources:
  - servers/status
  verbs:
  - get
  - patch
  - update
